[changelog]
header = "# Changelog"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
[{{ commit.id }}](https://github.com/jgalaber/node-virtual-enviroment-cli/commit/{{ commit.id }}) {{ commit.author.name }} on {{ commit.author.timestamp | date(format="%Y-%m-%d %H:%M") }} - {{ commit.message | trim }}
{% endfor %}
{% endfor %}
"""
trim = true
sort_commits = "newest"
filter_commits = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
tag_pattern = "v[0-9]*"
include_commits = true

commit_parsers = [
  { message = "^.*$", body = false, footers = false, timestamp = true, author = true }
]
